config/routes.rb
Rails.application.routes.draw do

  get 'portal_votante/inicio'
  get 'portal_votante/ingresar_vista_voto'
  get 'portal_votante/vista_voto'
  put 'portal_votante/ingresar_voto'

  resources :cabinas

  resources :poders
  resources :personas do
    member do
      put 'eliminar_asistencia'
      put 'agregar_asistencia'
      put 'eliminar_candidatura'
      put 'agregar_candidatura'
      put 'habilitar_voto'
      put 'habilitar_voto_manual'
      get 'nomina'
    end
    collection do
      post 'create_collection'
    end
  end

  resources :votacions do
    member do
      post 'avanzar_estado'
      post 'retroceder_estado'
      get 'edit_poderes_extra'
      put 'update_poderes_extra'
      get 'show_asistentes'
      get 'ingreso_masivo'
      get 'vista_vocal_de_mesa'
      get 'vista_vocal_de_mesa_manual'
      get 'resultados'
      get 'ingreso_votos_manuales'
      put 'aceptar_votos_manuales'
      get 'agregar_candidato'
    end
  end
  resources :users do
    member do
      put 'activate'
      put 'unactivate'
    end
  end

  get 'home/index'

   root 'sessions#new'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/invitado' => 'home#invitado'
  get '/home/ver_estado'

  get '/signup' => 'users#new'

  get '/permission_error' => 'home#permission_error', as: :permission_error

end

app/models/poder.rb
class Poder < ActiveRecord::Base
  belongs_to :poderante, class_name: "Persona"
  belongs_to :apoderado, class_name: "Persona"
  belongs_to :votacion
  validates :poderante_id, presence: true

  @@RELACIONES_PARTES = ['hijo','cónyuge','trabajador/administrador','otro']

  @@estados = ['válido', 'nulo por inasistencia del representante','nulo por asistencia del representado','nulo por poder más reciente']

  def self.estados_str
    return @@estados
  end

  def estado_str
    @@estados[self.estado]
  end

  def valido
    self.estado == 0
end

  def file_path
    return "/uploads/#{file_name}"
  end

  def self.relaciones_partes
    @@RELACIONES_PARTES
  end

  def relacion_partes_s
    @@RELACIONES_PARTES[self[:relacion_partes]]
  end

  def es_relacion_invalida?
    return self[:relacion_partes] == @@RELACIONES_PARTES.length - 1
  end

  def self.n_validos
    n = 0
    self.find_each do |poder|
      if poder.estado == 0
        n += 1
      end
    end
    n
  end

  def self.arreglo_estados
    arr = [0,0,0,0]
    self.find_each do |poder|
      arr[poder.estado] += 1
    end
    arr
  end

  def self.invalidos
    arr = []
    self.find_each do |poder|
      if poder.estado != 0
        arr.append(poder)
      end
    end
    arr
  end
  def estado
    poderante = self.poderante
    fecha = self.fecha_otorgamiento
    if self.poderante && self.poderante.estado != 0
      2
    elsif self.votacion && self.apoderado && self.votacion.estado > 1 && self.apoderado.estado == 0
      1
    else
      poderes_futuros = Poder.where(poderante: poderante).where.not(id: self.id).where('fecha_otorgamiento > ? OR (fecha_otorgamiento = ? AND id > ?)',fecha,fecha,self.id)
      if poderes_futuros.empty?
        0
      else
        3
      end
    end
  end



end

app/controllers/poders_controller.rb
class PodersController < ApplicationController
  before_action :set_poder, only: [:show, :edit, :update, :destroy]

  # GET /poders
  # GET /poders.json
  def index
    votacion_id =
    @votacion = Votacion.find(params[:votacion_id])
    @poders = @votacion.poders
    @rut = params[:rut]
    if @rut and @rut != ''
      @buscado_id = @votacion.personas.find_by_rut_string(@rut)
      @poders = @poders.where('poderante_id = ? OR apoderado_id = ?', @buscado_id,@buscado_id)
    end
    @per = 25
    @poders = @poders.page(params[:page]).per(@per)
  end

  # GET /poders/1
  # GET /poders/1.json
  def show
  end

  # GET /poders/new
  def new
    authorize_admin
    @poder = Poder.new
    @votacion_id = params[:votacion_id]
    @votacion = Votacion.find(@votacion_id)
    authorize_votacion_estados(@votacion,[0])
    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /poders/1/edit
  def edit
  end

  # POST /poders
  # POST /poders.json
  def create
    @poder = Poder.new(poder_params)
    @votacion = @poder.votacion
    if !authorize_votacion_estados(@votacion,[0]) || !authorize_admin
      return
    end
    poderante_rut = params[:poderante_rut]
    apoderado_rut = params[:apoderado_rut]
    if poderante_rut == apoderado_rut
      error = "¡Error! Representado y representante tienen el mismo rut"
      respond_to do |format|
        format.html   { render inline: error   }
        format.js { render inline: "alert('#{error}');" }
      end
      return
    end
    @poderante = Persona.where(votacion_id: @votacion.id,es_socio: true).find_by_rut_string(poderante_rut)
    if !@poderante
      error = "¡Error! El rut #{poderante_rut}  no corresponde a un socio de la cooperativa para la votacion #{@votacion.nombre}"
      respond_to do |format|
        format.html   { render inline: error   }
        format.js { render inline: "alert('#{error}');" }
      end
      return
    end
    apoderado_rut = params[:apoderado_rut]
    socio = params[:socio]
    @apoderado = nil
    if(!socio.nil? && socio == 'si')
      @apoderado = Persona.where(votacion_id: @votacion.id,es_socio: true).find_by_rut_string(apoderado_rut)
      if !@apoderado
        error = "¡Error! El rut #{apoderado_rut} no corresponde a un socio de la cooperativa para la votacion #{@votacion.nombre}"
        respond_to do |format|
          format.html   { render inline: error   }
          format.js { render inline: "alert('#{error}');" }
        end
        return
      end
      if !@apoderado.puede_ser_representante
        error = "¡Error! El rut #{apoderado_rut} corresponde a socio que no puede ser representante"
        respond_to do |format|
          format.html   { render inline: error   }
          format.js { render inline: "alert('#{error}');" }
        end
        return
      end
    else
      apoderado_nombre = params[:apoderado_nombre]
      @apoderado = get_or_create_persona(apoderado_rut,apoderado_nombre,@votacion.id)
    end
    @poder.poderante = @poderante
    @poder.apoderado = @apoderado
    if @poder.save
      #invalidar_antiguos(@poderante,@poder,@votacion)
      respond_to do |format|
        format.html { redirect_to @votacion }
        format.js { render inline: "alert('Poder agregado correctamente');window.location='#{votacion_url(init:'init', id: @votacion.id)}';" }
      end
    end
  end

  def get_or_create_persona(rut_persona, nombre_persona, votacion_id)
    @persona = Persona.where(votacion_id: votacion_id).find_by_rut_string(rut_persona)
    if @persona.nil?
      @persona = Persona.new(rut_string: rut_persona, nombre: nombre_persona, votacion_id: votacion_id, es_socio: false, fecha_ingreso: Date.today())
    end
    if @persona.save
      return @persona
    end
  end



  # PATCH/PUT /poders/1
  # PATCH/PUT /poders/1.json
  def update
    # respond_to do |format|
    #   if @poder.update(poder_params)
    #     format.html { redirect_to @poder, notice: 'Poder was successfully updated.' }
    #     format.json { render :show, status: :ok, location: @poder }
    #   else
    #     format.html { render :edit }
    #     format.json { render json: @poder.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # DELETE /poders/1
  # DELETE /poders/1.json
  def destroy
    @votacion = @poder.votacion
    @poder.destroy
    respond_to do |format|
      format.html { redirect_to poders_url(votacion_id: @votacion.id) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_poder
      @poder = Poder.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def poder_params
      params.require(:poder).permit(:relacion_partes, :fecha_otorgamiento, :votacion_id)
    end
end

app/helpers/poders_helper.rb
module PodersHelper
end

app/views/poders/_form.html.erb
<%= form_for(@poder, remote: true) do |f| %>
    <% if @poder.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@poder.errors.count, "error") %> prohibited this poder from being saved:</h2>
          <ul>
            <% @poder.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>


    <%= text_field_tag :apoderado_rut, nil, class: 'normal-form-field', placeholder: 'RUT representante' %><br>
    <%= text_field_tag :poderante_rut, nil, class: 'normal-form-field', placeholder: 'RUT representado' %><br>

    <div class="field">
      <%= f.label :fecha_otorgamiento%><br>
      <%= f.date_select :fecha_otorgamiento %>
    </div>

    <div class="field">
     ¿Representante es socio?<br>
      <%= radio_button_tag(:socio, "si",true) %>
      <%= label_tag(:socio_si, "Sí") %>&nbsp;
      <%= radio_button_tag(:socio, "no") %>
      <%= label_tag(:socio_no, "No") %>
    </div>

    <div id="no_socio" hidden>

      <%= text_field_tag :apoderado_nombre, nil, class: 'normal-form-field', placeholder: 'nombre representante' %><br>

      <div class="field">
        <%= label_tag :relacion_partes %><br>
        <% arreglo_partes = Poder.relaciones_partes.map { |relacion| [relacion, Poder.relaciones_partes.index(relacion)] } %>
        <%= f.select(:relacion_partes, arreglo_partes) %>
      </div>

    </div>

      <%= f.hidden_field :votacion_id, value: @votacion.id%>
    <div class="actions">
      <%= f.submit 'ingresar poder', class: 'boton-naranjo', id: "new-poder-submit" %>
      <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
    </div>
<% end %>

app/views/poders/_list.html.erb
<div class="col-md-8 col-md-offset-1">
  <div class="listing">


  <h4>Lista de poderes</h4>
    <% if params[:controller] == 'poders' %>
        <%= form_tag(poders_path(votacion_id: @votacion.id), method: "get") do %>
            <%= hidden_field_tag 'votacion_id', @votacion.id %>
            <%= text_field_tag(:rut, nil, placeholder: "Buscar por RUT")%><%= submit_tag 'Buscar', class: 'boton-naranjo' %><br>
        <% end %><br>
    <% end %>
    <%= paginate @poders %><br>
    <table class="table table-bordered">
      <thead>
      <tr>
        <th width="5%"> N°</th>
        <th width="15%">Representado</th>
        <th width="15%">Representante</th>
        <th width="15%">Fecha de otorgamiento</th>
        <th>Estado</th>
        <th colspan="1">
      </tr>
      </thead>

      <tbody>
      <% @i = 1 %>
      <% @poders.each do |poder| %>
        <tr>
          <td><%= @per*(-1+ @poders.current_page) + @i %></td>
          <% if poder.poderante.nil?%>
            <td>No tiene</td>
          <% else %>
            <td><%= link_to poder.poderante.rut_string, poder.poderante %></td>
          <%end%>
          <% if poder.apoderado.nil? %>
            <td>No tiene</td>
          <% else %>
            <td><%= link_to poder.apoderado.rut_string, poder.apoderado %></td>
          <%end%>
          <td><%= poder.fecha_otorgamiento %></td>
          <td><%= poder.estado_str %></td>
          <td class="td-ver">
            <% if current_user && current_user.es_admin_autorizado %>
                <%= button_to 'Eliminar', poder, class: 'boton-ver boton-poder eliminar', method: 'delete', 'data-toggle' => 'popover', 'data-trigger' => 'hover' %>
            <% end %>
          </td>
        </tr>
      <% @i += 1 %>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/poders/_new_poder_modal.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="normal-form" id="new-poder-form">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      <h4>Agregar poder</h4>
      <%= render 'form' %>
    </div>
  </div>
</div><!-- /.modal-dialog -->

app/views/poders/edit.html.erb
<h1>Editing Poder</h1>

<%= render 'form' %>

<%= link_to 'Show', @poder %> |
<%= link_to 'Back', poders_path %>

app/views/poders/index.html.erb
<div class="row titulo-seccion">
  <h3 class="menu-title">
    <span class="thin-underline"><%= @votacion.nombre %></span>
    <small><%= @votacion.fecha_realizacion %></small>
  </h3>
  </div>
<div class="row">
  <div class="col-md-12">
    <h4 class="menu-title">Poderes</h4>
    <div class="no-decor">
      <% if @votacion.estado == 0 %>
          <%= link_to '<span class="glyphicon glyphicon-plus" data-container="body" data-toggle="tooltip" data-placement="top" title="Agregar poderes"></span>'.html_safe, new_poder_path(params: {votacion_id: @votacion.id}), remote: true, 'data-backdrop' => true, 'data-toggle' => 'modal', 'data-target' => '#modal-new-poder', id:'agregar-poder'%>
      <%end%>
    </div>
  </div>
</div>


<div class="row">
    <%= render 'list' %>
</div>


<div class="modal modal-centrado fade" id="modal-new-poder" tabindex="-1" role="dialog"></div>

app/views/poders/new.html.erb
<h1>New Poder</h1>

<%= render 'form' %>

<%= link_to 'Back', poders_path %>

app/views/poders/new.js.erb
$('#modal-new-poder').html("<%= escape_javascript(render partial: 'new_poder_modal', object: @poder) %>");
socio_radio();
poder_rut_format();

app/views/poders/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <strong>Votación:</strong>
    <%= link_to @poder.votacion.nombre, @poder.votacion %>
</p>

<p>
  <strong>Poderante:</strong>
    <%= link_to @poder.poderante.rut_string, @poder.poderante %>
</p>

<p>
  <strong>Apoderado:</strong>
    <%= link_to @poder.apoderado.rut_string, @poder.apoderado %>
</p>

<p>
  <strong>Fecha de otorgamiento:</strong>
    <%= @poder.fecha_otorgamiento %>

</p>
<p>
  <strong>Es válido? </strong>
  <%= boolean_to_s(@poder.valido) %>
</p>

  <p>
    <% if @poder.apoderado.es_socio %>
    <% elsif @poder.es_relacion_invalida?  %>
      El apoderado no es un apoderdo válido.(No es socio de la cooperativa, cónyuge, hijo o trabajador del poderante)
    <% else %>
      El apoderado es <%=  @poder.relacion_partes_s  %> del poderante.
    <% end  %>
  </p>

<%= link_to 'Back', votacion_path(@poder.votacion) %>