config/routes.rb
Rails.application.routes.draw do

  get 'portal_votante/inicio'
  get 'portal_votante/ingresar_vista_voto'
  get 'portal_votante/vista_voto'
  put 'portal_votante/ingresar_voto'

  resources :cabinas

  resources :poders
  resources :personas do
    member do
      put 'eliminar_asistencia'
      put 'agregar_asistencia'
      put 'eliminar_candidatura'
      put 'agregar_candidatura'
      put 'habilitar_voto'
      put 'habilitar_voto_manual'
      get 'nomina'
    end
    collection do
      post 'create_collection'
    end
  end

  resources :votacions do
    member do
      post 'avanzar_estado'
      post 'retroceder_estado'
      get 'edit_poderes_extra'
      put 'update_poderes_extra'
      get 'show_asistentes'
      get 'ingreso_masivo'
      get 'vista_vocal_de_mesa'
      get 'vista_vocal_de_mesa_manual'
      get 'resultados'
      get 'ingreso_votos_manuales'
      put 'aceptar_votos_manuales'
      get 'agregar_candidato'
    end
  end
  resources :users do
    member do
      put 'activate'
      put 'unactivate'
    end
  end

  get 'home/index'

   root 'sessions#new'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/invitado' => 'home#invitado'
  get '/home/ver_estado'

  get '/signup' => 'users#new'

  get '/permission_error' => 'home#permission_error', as: :permission_error

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates_uniqueness_of :username
  before_save :default_values

  @@tipos = ['admin','vocal','tricel','control asistencia', 'super_admin','digitador']

  def self.tipos
    return @@tipos
  end

  def tipo_str
    @@tipos[self.tipo]
  end

  def es_admin_autorizado
    es_tipo_autorizado(0)
  end

  def es_vocal_autorizado
    es_tipo_autorizado(1)
  end

  def es_tricel_autorizado
    es_tipo_autorizado(2)
  end

  def es_control_asistencia_autorizado
    es_tipo_autorizado(3)
  end

  private
  def es_tipo_autorizado(n_tipo)
    (self.tipo == n_tipo || self.tipo == 0 || self.tipo == 4) && self.auth
  end

  def default_values
    self.tipo ||= 1
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :activate, :unactivate]
  skip_before_action :login_redirect, only: [:new, :create]

  # GET /users
  # GET /users.json
  def index
    authorize_admin
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    authorize_user(@user)
  end

  # GET /users/new
  def new
    @user = User.new(tipo:nil)
    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /users/1/edit
  def edit
    authorize_user(@user)
  end

  def activate
    if !authorize_admin
      return
    end
    @user.auth = true
    if @user.save
      redirect_to users_path
    end
  end

  def unactivate
    if !authorize_admin
      return
    end
    @user.auth = false
    if @user.save
      redirect_to users_path
    end
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    @user.auth = true
    if User.all.empty?
      @user.tipo= 4
      @user.auth = true
    end
    if @user.save
      redirect_to users_path
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    authorize_user(@user)
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :password, :password_confirmation, :tipo, :auth)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
    <%= form_for(@user) do |f| %>
      <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@user.errors.count, "error") %> prohibieron que este usuario se guardara:</h2>
          <ul>
            <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <%= f.text_field :username, class: 'normal-form-field', placeholder: 'Nombre de usuario' %><br>
      <%= f.password_field :password, class: 'normal-form-field', placeholder: 'Contraseña' %><br>
      <%= f.password_field :password_confirmation, class: 'normal-form-field', placeholder: 'Repetir contraseña' %><br>
      <% arreglo_tipos = User.tipos.map { |tipo| [tipo, User.tipos.index(tipo)] } %>
      <%= f.select :tipo, arreglo_tipos[0..-2],{prompt: 'Tipo de usuario'}, { :class => 'normal-form-field' } %>
      <%= f.submit "Agregar", class: 'boton-naranjo', id: "new-user-submit" %>
    <% end %>

app/views/users/_listing.html.erb
<div class="col-md-8 listing-usuarios listing">

<h4>Lista de usuarios</h4>

<table class="table table-bordered table-usuarios">
  <thead>
  <tr>
    <th>Nombre de usuario</th>
    <th>Tipo de usuario</th>
    <th colspan="2"></th>
  </tr>
  </thead>

  <tbody>
  <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.tipo_str %></td>
        <td class="td-ver">
          <%#= button_to 'Ver', user, method: 'get', class: 'boton-ver' %>
          <% if current_user && current_user.es_admin_autorizado && user.tipo != 4 %>
            <%= button_to 'Eliminar', user, method: :delete, data: { confirm: '¿Esá seguro que desea eliminar este usuario?' }, class: 'boton-ver' %>
          <% end %>
        </td>
        <td class="td-ver">
          <% if current_user && current_user.es_admin_autorizado && user.tipo != 4 %>
              <% if user.auth %>
                  <%= button_to "Autorizado", unactivate_user_path(user), method: :put, class: 'boton-aut' %>
              <% else %>
                  <%= button_to "Desautorizado", activate_user_path(user), method: :put, class: 'boton-aut inactivo' %>
              <% end %>
          <% end %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

</div>

app/views/users/_new_user.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="normal-form" id="new-user-form">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <%= render 'form' %>
      </div>
  </div>
</div><!-- /.modal-dialog -->

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<div class="usuarios">
  <div class="row titulo-seccion"><h3><span class="thin-underline">Usuarios</span></h3></div>
  <div class="row seccion">
      <%= render 'listing' %>
    <div class="col-md-2">
      <%= link_to new_user_path, class: 'btn btn-default boton-gris', id: 'nuevo_usuario', remote: true, 'data-backdrop' => true, 'data-toggle' => 'modal', 'data-target' => '#modal-new-user' do %>
          <strong><span class="mas">+</span></strong> Nuevo <span class="weigth-500">usuario</span>
      <% end %>
    </div>
  </div>
</div>


<div class="modal fade" id="modal-new-user" tabindex="-1" role="dialog"></div>

app/views/users/new.html.erb
<h1>Nuevo usuario</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/new.js.erb
$('#modal-new-user').html("<%= escape_javascript(render partial: 'new_user', object: @user) %>");

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Tipo:</strong>
  <%= @user.tipo_str %>
</p>

<p>
  <strong>Auth:</strong>
  <%= @user.auth %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>