config/routes.rb
Rails.application.routes.draw do

  get 'portal_votante/inicio'
  get 'portal_votante/ingresar_vista_voto'
  get 'portal_votante/vista_voto'
  put 'portal_votante/ingresar_voto'

  resources :cabinas

  resources :poders
  resources :personas do
    member do
      put 'eliminar_asistencia'
      put 'agregar_asistencia'
      put 'eliminar_candidatura'
      put 'agregar_candidatura'
      put 'habilitar_voto'
      put 'habilitar_voto_manual'
      get 'nomina'
    end
    collection do
      post 'create_collection'
    end
  end

  resources :votacions do
    member do
      post 'avanzar_estado'
      post 'retroceder_estado'
      get 'edit_poderes_extra'
      put 'update_poderes_extra'
      get 'show_asistentes'
      get 'ingreso_masivo'
      get 'vista_vocal_de_mesa'
      get 'vista_vocal_de_mesa_manual'
      get 'resultados'
      get 'ingreso_votos_manuales'
      put 'aceptar_votos_manuales'
      get 'agregar_candidato'
    end
  end
  resources :users do
    member do
      put 'activate'
      put 'unactivate'
    end
  end

  get 'home/index'

   root 'sessions#new'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/invitado' => 'home#invitado'
  get '/home/ver_estado'

  get '/signup' => 'users#new'

  get '/permission_error' => 'home#permission_error', as: :permission_error

end

app/models/votacion.rb
class Votacion < ActiveRecord::Base
  has_many :personas
  has_many :poders
  has_many :tiempo_de_votacions
  has_many :cabinas
  before_save :default_values

  @@estados = ['backoffice','control asistencia','ingreso de candidatos','en transcurso','ingreso manual de votos','cerrada']

  def estado_str
    @@estados[estado]
  end

  def asiste?(persona)
    self.asistentes.include?(persona)
  end

  def get_siguiente_cabina
    cabinas = self.cabinas
    n_cabinas_actual = cabinas.size
    sig = (self.sig_indice_cabina + 1) % n_cabinas_actual
    result = cabinas[self.sig_indice_cabina]
    self.update_attribute(:sig_indice_cabina,sig)
    return result
  end

  def asistentes
    self.personas.where.not(estado: 0).order(hora_asistencia: :desc)
  end

  def num_cabinas_disponibles
    disponibles = (1..self.n_cabinas).to_a
    cabinas = self.cabinas
    cabinas.each do |c|
      num = c.number
      disponibles.delete(num)
    end
    disponibles
  end

  def n_asistentes
    self.asistentes.size
  end

  def total_votos_electronicos_segun_resultados
    resultado = self.votos_nulos_electronicos + self.votos_blancos_y_fuera_de_tiempo_electronicos
    self.candidatos.find_each do |candidato|
      resultado += candidato.votos_recibidos_electronicos
    end
    resultado
  end

  def total_votos_manuales_segun_resultados
    resultado = self.votos_nulos_manuales + self.votos_blancos_manuales
    self.candidatos.find_each do |candidato|
      resultado += candidato.votos_recibidos_manuales
    end
    resultado
  end


  def total_votos_segun_votantes
    self.total_votos_manuales_segun_votantes + self.total_votos_electronicos_segun_votantes
  end

  def total_votos_segun_resultados
    self.total_votos_electronicos_segun_resultados + self.total_votos_manuales_segun_resultados
  end


  def votos_nulos_totales
    self.votos_nulos_electronicos + self.votos_nulos_manuales
  end

  def votos_blancos_totales
    self.votos_blancos_y_fuera_de_tiempo_electronicos + self.votos_blancos_manuales
  end

  def votos_blancos_y_fuera_de_tiempo_electronicos
    self.votos_fuera_de_tiempo + self.votos_blancos_electronicos
  end

  def votantes_fuera_de_tiempo
    self.personas.where(ha_votado: false).joins(:tiempo_de_votacions).uniq
  end

  def votos_fuera_de_tiempo
    fuera_de_tiempo = 0
    self.personas.where(ha_votado: false).joins(:tiempo_de_votacions).uniq.find_each do |persona|
      fuera_de_tiempo += persona.votos_totales_disponibles
    end
    fuera_de_tiempo

  end

  def n_poderes_totales
    self.poders.size + self.n_blancos +  self.n_nulos_forma + self.n_nulos_plazo
  end

  def total_maxima_representacion
    n_asistentes_y_representados = self.asistentes.size + self.poders.n_validos
    resultado = n_asistentes_y_representados * self.max_representacion / 100.0
    resultado.round
  end

  def pueden_ser_candidatos
    Persona.pueden_ser_candidatos.where(votacion_id: self.id)
  end

  def candidatos
    self.personas.where('estado > ?',1)
  end


  def poderes_invalidos
    self.poders.invalidos
  end

  def self.activas
    Votacion.where.not(estado: Votacion.estado_cerrada)
  end

  def self.activa
    Votacion.where.not(estado: Votacion.estado_cerrada).take
  end

  def self.estado_cerrada
    @@estados.length - 1
  end

  def sig_estado_str
    otro_estado_str(1)
  end

  def self.estados
    return @@estados
  end

  def ant_estado_str
    otro_estado_str(-1)
  end


  private
  def otro_estado_str(dif)
    nuevo = self.estado + dif
    if nuevo < 0   || nuevo >= @@estados.length
      nil
    else
      @@estados[nuevo]
    end
  end

  def default_values
    self.max_representacion ||= 3
    self.n_ganadores ||= 1
    self.max_minutos_voto ||= 5
    self.n_cabinas ||= 1
  end


end

app/controllers/votacions_controller.rb
class VotacionsController < ApplicationController
  before_action :set_votacion, only: [:show, :edit, :update, :destroy, :edit_poderes_extra, :update_poderes_extra, :avanzar_estado, :retroceder_estado, :show_asistentes, :ingreso_masivo, :vista_vocal_de_mesa, :vista_vocal_de_mesa_manual, :ingreso_votos_manuales, :aceptar_votos_manuales, :resultados, :agregar_candidato]


  # GET /votacions
  # GET /votacions.json
  def index
    @votacions = Votacion.all
  end

  # GET /votacions/1
  # GET /votacions/1.json
  def show
    @sig = @votacion.sig_estado_str
    @ant = @votacion.ant_estado_str
    @asistentes = @votacion.personas
    @pueden_ser_candidatos = Persona.pueden_ser_candidatos(@votacion.personas)
    @candidatos = @votacion.candidatos
    @estados_poderes = @votacion.poders.arreglo_estados
    @nombres_estados_poderes = @votacion.poders.estados_str
    @n_cabinas_disponibles = @votacion.num_cabinas_disponibles
    @mensaje = params[:mensaje]
    @init = params[:init]
  end

  # GET /votacions/new
  def new
    authorize_admin
    @votacion = Votacion.new(max_representacion: nil, n_ganadores: nil, n_cabinas: nil, max_minutos_voto: nil)
    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /votacions/1/edit
  def edit
    authorize_admin
    authorize_votacion_estados(@votacion,[0])
  end

  # POST /votacions
  # POST /votacions.json
  def create
    authorize_admin
    @votacion = Votacion.new(votacion_params)
    if @votacion.save
      redirect_to votacions_path
    else
      render :new
    end
  end

  # PATCH/PUT /votacions/1
  # PATCH/PUT /votacions/1.json
  def update
    authorize_admin
    authorize_votacion_estados(@votacion,[0])
    respond_to do |format|
      if @votacion.update(votacion_params)
        format.html { redirect_to @votacion, notice: 'Votacion was successfully updated.' }
        format.json { render :show, status: :ok, location: @votacion }
      else
        format.html { render :edit }
        format.json { render json: @votacion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /votacions/1
  # DELETE /votacions/1.json
  def destroy
    authorize_admin
    @votacion.cabinas.destroy_all
    @votacion.destroy
    respond_to do |format|
      format.html { redirect_to votacions_url}
      format.json { head :no_content }
    end
  end

  def resultados
    authorize_votacion_estados(@votacion,[3,4,5])
    @candidatos = @votacion.candidatos
  end

  def show_asistentes
    authorize_asistencia
    authorize_votacion_estados(@votacion,[1,2,3,4,5])
    @per = 25
    @personas = @votacion.asistentes.page(params[:page]).per(@per)
    @asistentes = true
    @agregar = params[:agregar]
  end

  def edit_poderes_extra
    authorize_admin
    authorize_votacion_estados(@votacion,[0])
    respond_to do |format|
      format.html
      format.js
    end
  end

  def agregar_candidato
    authorize_tricel
    respond_to do |format|
      format.js
      format.html
    end
  end

  def update_poderes_extra
    authorize_admin
    authorize_votacion_estados(@votacion,[0])
    respond_to do |format|
      if @votacion.update(votacion_params)
        format.html { redirect_to @votacion, notice: 'Votacion was successfully updated.' }
        format.json { render :show, status: :ok, location: @votacion }
      else
        format.html { render :edit }
        format.json { render json: @votacion.errors, status: :unprocessable_entity }
      end
    end
  end

  def ingreso_votos_manuales
    authorize_tricel
    authorize_votacion_estados(@votacion,[4])
    @blancos = @votacion.votos_blancos_manuales
    @nulos = @votacion.votos_nulos_manuales
    @candidatos = @votacion.candidatos
    @n_votos_disponibles = @votacion.total_votos_manuales_segun_votantes
  end

  def aceptar_votos_manuales
    authorize_tricel
    authorize_votacion_estados(@votacion,[4])
    @candidatos = @votacion.candidatos
    @candidatos.each do |c|
      c.votos_recibidos_manuales = params[c.id.to_s].to_i
      c.save
    end
    @votacion.votos_nulos_manuales = params[:nulos].to_i
    @votacion.votos_blancos_manuales = params[:blancos].to_i
    @votacion.save
    redirect_to @votacion
  end

  def avanzar_estado
    authorize_admin
    @votacion.estado +=1
    @votacion.save
    redirect_to @votacion
  end

  def retroceder_estado
    authorize_admin
    @votacion.estado -= 1
    @votacion.save
    redirect_to @votacion
  end

  def vista_vocal_de_mesa
    authorize_vocal
    authorize_votacion_estados(@votacion,[3])
    @sesiones = @votacion.tiempo_de_votacions
  end

  def vista_vocal_de_mesa_manual
    authorize_vocal
    authorize_votacion_estados(@votacion,[3])
    @sesiones = @votacion.tiempo_de_votacions
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_votacion
    @votacion = Votacion.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def votacion_params
    params.require(:votacion).permit(:nombre, :fecha_realizacion, :max_representacion, :n_blancos, :n_nulos_forma, :n_nulos_plazo, :n_ganadores, :max_minutos_voto, :n_cabinas)
  end




end

app/helpers/votacions_helper.rb
module VotacionsHelper
end

app/views/votacions/_modal_agregar_candidato.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="normal-form" id="new-poder-form">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      <h4>Ingreso de candidato</h4>
      <%= form_tag agregar_candidatura_persona_path(votacion_id: @votacion.id), method: :put, remote: true do %>
          <%= text_field_tag :rut, nil, class: 'normal-form-field', placeholder: 'RUT'%><br>
          <%= submit_tag "ingresar", class: 'boton-naranjo' %><br>
      <% end %>
    </div>
  </div>

</div>

app/views/votacions/_pie_chart.html.erb
<script>
  var tipo= <%= @tipo %>;
  <%@candidatos.sort_by { |f | [f.votos_recibidos_totales] }%>
    colors = ['#575756', '#878787', '#9D9D9C', '#B2B2B2', '#C6C6C6', '#DADADA', '#EDEDED', '#F6F6F6'];
    var data<%= @tipo %> = [
        {
            "index": 0,
            "label": "Blancos",
            "electo": false,
            "value":<%=
            if @tipo == 1
                @votacion.votos_blancos_totales
            elsif @tipo==2
                @votacion.votos_blancos_electronicos
            else
                @votacion.votos_blancos_manuales
            end%>
        },
        {
            "index": 1,
            "label": "Nulos",
            "electo": false,
            "value": <%=
            if @tipo == 1
                @votacion.votos_nulos_totales
            elsif @tipo==2
                @votacion.votos_nulos_electronicos
            else
                @votacion.votos_nulos_manuales
            end%>
        },
        <% @i = 2 %>
        <% @candidatos.each do |candidato| %>
        {
            "index": <%= @i %>,
            "label": "<%= candidato.nombre_resultado %>",
            "electo": <%= candidato.electo %>,
            "value": <%=
            if @tipo == 1
                candidato.votos_recibidos_totales
            elsif @tipo == 2
                candidato.votos_recibidos_electronicos
            else
                candidato.votos_recibidos_manuales
            end%>,
            "color":"white"
        <% @i+= 1 %>
        },
        <% end %>
    ];

    nv.addGraph(function () {
        var chart = nv.models.pieChart()
                        .x(function (d) {
                            return d.label
                        })
                        .y(function (d) {
                            return d.value
                        })
                        .donut(true)
                        .showLegend(false)
                        .donutRatio(0.35)
                        .labelThreshold(0.05)
                        .valueFormat(d3.format(",.0f"))
                        .color(function(d){
                            if (d.data.electo){
                                return "#FB7824";
                            }
                            return colors[d.data.index % colors.length];})
                        .growOnHover(true)
                        .tooltipContent(function(key, y, e, graph) { return '<h6 class="chart" style="background-color:'
                                + e.color+'">' + key + '</h6>' +
                                '<p>' +  y + '</p>' })

                <%# if @tipo == 1%>
                    <%=".donutLabelsOutside(true)"%>
                <%# end %>
                <% if @tipo== 2 || @tipo == 3%>
                    <%#=".showLegend(false)"%>
                    <%#=".donutLabelsOutside(false)"%>
                    <%#=".showLabels(false)"%>
                <% end %>
                ;
        d3.select("#pie-chart-<%="#{@votacion.id}-#{@tipo}"%> svg")
                .datum(data<%= @tipo %>)
                .transition().duration(1200)
                .call(chart)
                .selectAll('.nv-label text').call(wrap2, 60);

        return chart;
    });

  formatPieChart();

  function wrap2(text, width) {
      text.each(function() {
          var text = d3.select(this),
                  words = text.text().split(/\s+/).reverse(),
                  word,
                  line = [],
                  lineNumber = 0,
                  lineHeight = 1.2, // ems
                  y = text.attr("y"),
                  tspan = text.text(null).append("tspan").attr("x", 0).attr("y", y).attr("dy", "0em");
          while (word = words.pop()) {
              line.push(word);
              tspan.text(line.join(" "));
              if (tspan.node().getComputedTextLength() > width) {
                  line.pop();
                  tspan.text(line.join(" "));
                  line = [word];
                  tspan = text.append("tspan").attr("x", 0).attr("y", y).attr("dy", lineHeight + "em").text(word);
              }
          }
      });
  }
</script>

app/views/votacions/_poderes_bar_chart.html.erb
<% @estados_poderes = local_assigns[:estados_poderes] %>
<% @nombres_estados_poderes = local_assigns[:nombres_estados_poderes] %>

<script>
    var colors = ['#424242', '#575756', '#878787', '#9D9D9C', '#B2B2B2', '#C6C6C6', '#DADADA', '#EDEDED']

    nv.addGraph(function () {
        var chart = nv.models.discreteBarChart()
                        .x(function (d) {
                            return d.label
                        })
                        .y(function (d) {
                            return d.value
                        })
                        //.staggerLabels(true)
                        .tooltips(false)
                        .showValues(true)
                        .showYAxis(false)
                        .valueFormat(d3.format(",.0f"))
                        .color(colors)


                ;

        d3.select('#poderes-chart svg')
                .datum(exampleData())
                .call(chart);
        var te = d3.selectAll('#poderes-chart svg').selectAll('.tick text');
        te.call(wrap, 100);


        nv.utils.windowResize(chart.update);

        return chart;
    });

    //Each bar represents a single discrete quantity.
    function exampleData() {
        return [
            {
                key: "Poderes",
                values: [
                    {
                        "label": "<%= @nombres_estados_poderes[0] %>",
                        "value": <%= @estados_poderes[0] %>
                    },
                    {
                        "label": "<%= @nombres_estados_poderes[1] %>",
                        "value": <%= @estados_poderes[1] %>
                    },
                    {
                        "label": "<%= @nombres_estados_poderes[2] %>",
                        "value": <%= @estados_poderes[2] %>
                    },
                    {
                        "label": "<%= @nombres_estados_poderes[3] %>",
                        "value": <%= @estados_poderes[3] %>
                    },
                    {
                        "label": "blancos",
                        "value": <%= @votacion.n_blancos %>
                    },
                    {
                        "label": "nulos fuera de plazo",
                        "value": <%= @votacion.n_nulos_plazo %>
                    },
                    {
                        "label": "nulos por forma",
                        "value": <%= @votacion.n_nulos_forma %>
                    },
                ]
            }
        ]

    }
    function wrap(text, width) {
        text.each(function() {
            var text = d3.select(this),
                    words = text.text().split(/\s+/).reverse(),
                    word,
                    line = [],
                    lineNumber = 0,
                    lineHeight = 1.1, // ems
                    y = text.attr("y"),
                    dy = parseFloat(text.attr("dy")),
                    tspan = text.text(null).append("tspan").attr("x", 0).attr("y", y).attr("dy", dy + "em");
            while (word = words.pop()) {
                line.push(word);
                tspan.text(line.join(" "));
                if (tspan.node().getComputedTextLength() > width) {
                    line.pop();
                    tspan.text(line.join(" "));
                    line = [word];
                    tspan = text.append("tspan").attr("x", 0).attr("y", y).attr("dy", ++lineNumber * lineHeight + dy + "em").text(word);
                }
            }
        });
    }
</script>

app/views/votacions/_popover.html.erb
<% votacion = local_assigns[:var_votacion] %>
<h5>Candidatos</h5>
<div>
  <div id="chart">
    <svg></svg>
  </div>
  <script>
      var h = 400;
      var r = h / 2;
      var arc = d3.svg.arc().outerRadius(r);

      var data = [
          {"label": "Colorectale levermetastase (n=336)", "value": 74},
          {"label": "Levensmetatase van andere origine (n=32)", "value": 7},
          {"label": "Beningne levertumor (n=34)", "value": 7},
          {"label": "Primaire maligne levertumor (n=56)", "value": 12}
      ];

      var colors = ['#575756', '#878787', '#9D9D9C', '#B2B2B2', '#C6C6C6', '#DADADA', '#EDEDED', '#F6F6F6']
      nv.addGraph(function () {
          var chart = nv.models.pieChart()
                          .x(function (d) {
                              return d.label
                          })
                          .y(function (d) {
                              return d.value
                          })
                          .color(colors)
                          .showLabels(true)
                          .showLegend(false)
                          .valueFormat(d3.format(",.0f"))
                          .labelType("percent")
                          .donut(true).donutRatio(0)
          //.tooltip.enabled(false)
                  ;

          d3.select("#chart svg")
                  .datum(data)
                  .transition().duration(1200)
                  .call(chart);

          return chart;
      });

  </script>

</div>
<h5>Socios y representantes</h5>
<h5>Poderes</h5>

app/views/votacions/agregar_candidato.js.erb
$('#modal-agregar-candidato').html("<%= escape_javascript(render partial: 'modal_agregar_candidato') %>");
formatRutField();

app/views/votacions/edit.html.erb
<div class="row titulo-seccion">
  <h3 class="menu-title">
    <span class="thin-underline"><%= @votacion.nombre %></span>
    <small><%= @votacion.fecha_realizacion %></small>
  </h3>
  <h4>Editar votación</h4>
</div>
<div class="row">

</div>
<div class="row">
  <div class="col-md-6 col-md-offset-3">

    <div class="listing">
    <% if @votacion.estado == 0 %>
        <%= form_for(@votacion) do |f| %>
            <div class="edit-votacion">
              <table class="table table-bordered">
                <tr>
                  <td>Porcentaje máximo de representación</td>
                  <td class="fondo-transparente-F6F6F6 align-center">
                    <%= f.number_field :max_representacion, class: 'align-center' %>
                  </td>
                </tr>
                <tr>
                  <td>Tiempo máximo votación (minutos)</td>
                  <td class="fondo-transparente-F6F6F6 align-center">
                    <%= f.number_field :max_minutos_voto, class: 'align-center' %>
                  </td>
                </tr>
                <tr>
                  <td>Máximo número de cabinas de votación</td>
                  <td class="fondo-transparente-F6F6F6 align-center">
                    <%= f.number_field :n_cabinas, class: 'align-center' %>
                  </td>
                </tr>
                <tr>
                  <td>Número de electos</td>
                  <td class="fondo-transparente-F6F6F6 align-center">
                    <%= f.number_field :n_ganadores, class: 'align-center' %>
                  </td>
                </tr>
                <tr>
                  <td>Fecha de realización</td>
                  <td class="fondo-transparente-F6F6F6 align-center">
                    <%= f.date_select :fecha_realizacion, class: 'align-center' %>
                  </td>
                </tr>
              </table>
            </div>
            <div class="actions">
              <%= f.submit 'Actualizar datos', class: 'boton-naranjo center' %>
            </div>
        <% end %>
          </div>
    <% else %>
        <p>No puede realizar modificaciones a esta votación ya que su estado es
          <% @votacion.estado %></p>
    <% end %>
  </div>
</div>

app/views/votacions/edit_poderes_extra.html.erb
<%= render 'form_edit_poderes_extra' %>

app/views/votacions/ingreso_masivo.html.erb
<%= render 'form_ingreso_masivo'%>

app/views/votacions/ingreso_masivo.js.erb
$('#modal-ingreso-masivo').html("<%= escape_javascript(render partial: 'form_ingreso_masivo', object: @votacion) %>");

app/views/votacions/new.html.erb
<h1>Nueva Votación</h1>

<%= render 'form' %>

<%= link_to 'Back', votacions_path %>

app/views/votacions/new.js.erb
$('#modal-new-votacion').html("<%= escape_javascript(render partial: 'new_votacion', object: @votacion) %>");

app/views/votacions/show_asistentes.html.erb
<% modo = local_assigns[:modo] %>
<div class="row titulo-seccion">
  <h3 class="menu-title">
    <span class="thin-underline"><%= @votacion.nombre %></span>
    <small><%= @votacion.fecha_realizacion %></small>
  </h3>
  <h4>Asistentes</h4>
</div>

<% if @votacion.estado == 1 && @agregar%>
<div class="row">
  <div class="col-md-4 col-md-offset-2">
    <strong>Agregar asistente</strong><br>
    <%= form_tag agregar_asistencia_persona_path(votacion_id: @votacion.id), class: "form-inline" ,method: :put, remote: true do %>
        <div class="form-group">
          <label class="sr-only" for="rut">Rut</label>
          <%= text_field_tag :rut,nil, class: 'form-control', placeholder: 'RUT' %>
        </div>
        <%= submit_tag :Aceptar, class: 'enviar-persona boton-naranjo' %>
<% end %>
  </div>
</div>
<% end %>
<div class="row">
<%= render 'personas/list', filtro: @filtro %>
</div>

app/views/votacions/vista_vocal_de_mesa.html.erb
<div class="row titulo-seccion">
  <h3 class="menu-title">
    <span class="thin-underline"><%= @votacion.nombre %></span>
    <small><%= @votacion.fecha_realizacion %></small>
  </h3>
  <h4>Vocal de mesa para <strong>votación electrónica</strong></h4>
</div>
<div class="row">
  <div class="col-md-4 col-md-offset-2">
Habilitar usuario para <strong>votación electrónica</strong><br>
<%= form_tag habilitar_voto_persona_path(votacion_id: @votacion.id),class: 'form-inline', method: :put, remote: true do %>
        <div class="form-group">
          <label class="sr-only" for="rut">Rut</label>
          <%= text_field_tag :rut,nil, class: 'form-control', placeholder: 'RUT' %>
        </div>
        <%= submit_tag :Aceptar, class: 'enviar-persona boton-naranjo' %>
<% end %>

  </div>
</div>
<div class="row">
  <div class="col-md-10 col-md-offset-1">
<div class="listing">
  <h4>Usuarios habilitados para votar</h4>
  <table class="table table-bordered">
  <thead>
  <tr>
    <th width="5%">N°</th>
    <th width="15%">Rut</th>
    <th width="30%">Nombre</th>
    <th width="10%">Cabina de votacion</th>
    <th width="10%">Votos disponibles</th>
    <th width="10%">¿Votó?</th>
    <th width="10%">Nómina</th>
  </tr>
  </thead>

  <tbody>
  <% @i = 1 %>
  <% @sesiones.reverse_each do |sesion| %>
      <tr>
        <% persona = sesion.persona %>
        <td><%= @i %></td>
        <td><%= persona.rut_string %></td>
        <td><%= persona.nombre %></td>
        <td><%= if persona.cabina then persona.cabina.number else "Votación manual" end %></td>
        <td><%= persona.votos_totales_disponibles %></td>
        <td><%= boolean_to_s(persona.ha_votado) %></td>
        <td><%= button_to 'Generar', nomina_persona_path(persona), class: 'boton-ver', method: :get%></td>
        <% @i += 1 %>
      </tr>
  <% end %>
  </tbody>
</table>
    </div>
</div>
</div>