config/routes.rb
Rails.application.routes.draw do

  get 'portal_votante/inicio'
  get 'portal_votante/ingresar_vista_voto'
  get 'portal_votante/vista_voto'
  put 'portal_votante/ingresar_voto'

  resources :cabinas

  resources :poders
  resources :personas do
    member do
      put 'eliminar_asistencia'
      put 'agregar_asistencia'
      put 'eliminar_candidatura'
      put 'agregar_candidatura'
      put 'habilitar_voto'
      put 'habilitar_voto_manual'
      get 'nomina'
    end
    collection do
      post 'create_collection'
    end
  end

  resources :votacions do
    member do
      post 'avanzar_estado'
      post 'retroceder_estado'
      get 'edit_poderes_extra'
      put 'update_poderes_extra'
      get 'show_asistentes'
      get 'ingreso_masivo'
      get 'vista_vocal_de_mesa'
      get 'vista_vocal_de_mesa_manual'
      get 'resultados'
      get 'ingreso_votos_manuales'
      put 'aceptar_votos_manuales'
      get 'agregar_candidato'
    end
  end
  resources :users do
    member do
      put 'activate'
      put 'unactivate'
    end
  end

  get 'home/index'

   root 'sessions#new'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/invitado' => 'home#invitado'
  get '/home/ver_estado'

  get '/signup' => 'users#new'

  get '/permission_error' => 'home#permission_error', as: :permission_error

end

app/models/persona.rb
module NumberModelHelper
  include ActionView::Helpers::NumberHelper

  def format_number(integer)
    number_with_delimiter(integer, delimiter:'.')
  end

  def calcular_verificador(number)
    multiplicadores = [2,3,4,5,6,7]
    m_length = multiplicadores.length
    num_s = number.to_s
    num_length = num_s.length
    result = 0
    for i in (0..(num_length-1))
      index = -1 * (i+1)
      digito_acutal = num_s[num_length+index].to_i
      multiplicador = multiplicadores[i%m_length]
      result += digito_acutal*multiplicador
    end
    result = 11 - (result % 11)
    if(result == 11)
      return '0'
    elsif (result == 10)
      return 'K'
    else
      return result.to_s
    end
  end

  def rut_to_int(rut_string)
    cuerpo = rut_string.gsub('.','').gsub('-','')[0..-2].to_i
    verificador = rut_string[-1]
    v = calcular_verificador(cuerpo)
    if verificador == v
      return cuerpo
    else
      return nil
    end
  end

  # calcularVerificador = function(num){
  #   multiplicadores = [2,3,4,5,6,7];
  #   m_length = multiplicadores.length;
  #   num_s = num.toString();
  #   num_length = num_s.length;
  #   result = 0;
  #   for (i = 0; i < num_length; i++) {
  #       index = -1 * (i+1);
  #   digito_actual = parseInt(num_s.charAt(num_length+index));
  #   multiplicador = multiplicadores[i%m_length];
  #   result += digito_actual*multiplicador;
  #   }
  #   result = 11 - (result%11);
  #   if(result == 11){
  #       return '0';
  #   } else if (result == 10){
  #       return 'K';
  #   } else {
  #       return result.toString();
  #   }
  #   };
end

class Persona < ActiveRecord::Base
  include NumberModelHelper
  extend NumberModelHelper
  has_many :poderes_recibidos,  class_name: "Poder", foreign_key: "apoderado_id"
  has_many :poderes_enviados, class_name: "Poder", foreign_key: "poderante_id"
  has_many :tiempo_de_votacions
  belongs_to :votacion
  validates_uniqueness_of :rut_int, :scope => :votacion_id
  @@estados = ['Ausente', 'Asistente','Candidato']
  @@estados_voto = ['No ha votado','Está votando','Ya votó','Fuera de tiempo']
  @@tipos_voto = ['No ha votado','Electronico','Manual']

  def tipo_voto_str
    @@tipos_voto[self.tipo_voto]
  end

  def electo
      votacion = self.votacion
      n_vacantes = self.votacion.n_ganadores
      candidatos = votacion.candidatos.sort_by { |c| -1*c.votos_recibidos_totales}
      ultimo = nil
      for i in 0..(n_vacantes-1)
        ultimo = candidatos[i]
        if candidatos[i] == self
          return true
        end
      end
      if ultimo and ultimo.votos_recibidos_totales == self.votos_recibidos_totales
        return true
      end
    return false
  end

  # def self.no_han_votado
  #   arr = self.where.not(estado:0)
  #   result = []
  #   arr.each do |p|
  #     if p.estado_voto != 2
  #       result.append(p)
  #     end
  #   end
  #   r_map = result.map{|r| r.id}
  #   Persona.where(id: r_map)
  # end

  def self.no_han_votado
    self.where.not(estado: 0).where(ha_votado: false)
  end



  def estado_str
    @@estados[self.estado]
  end

  def ultima_sesion
    self.tiempo_de_votacions.last
  end

  def estado_voto
    ultima_sesion = self.ultima_sesion
    if ultima_sesion == nil
      return 0
    elsif ultima_sesion.activa && !self.ha_votado
      return 1
    elsif self.ha_votado
      return 2
    else
      return 3
    end
  end

  def estado_voto_str
    @@estados_voto[self.estado_voto]
  end

  def rut_string
    rut_i = self[:rut_int]
    if(!rut_i.nil?)
      format_number(rut_i) + '-' + calcular_verificador(rut_i)
    end
  end

  def info
    "#{self.rut_string} #{self.nombre}"
  end

  def nombre_resultado
    result = self.nombre
    if self.electo
      result += ' (ELECTO/A)'
    end
    result
  end

  def rut_string=(value)
    rut = rut_to_int(value)
    write_attribute(:rut_int,rut) unless rut.nil?
    return rut
  end

  def habilitar
    votacion = self.votacion
    cabina = votacion.get_siguiente_cabina
    self.update_attribute(:tipo_voto,1)
    tiempo_de_votacion = TiempoDeVotacion.create(persona_id: self.id, cabina: cabina, votacion_id: self.votacion.id)
    return cabina.number
  end

  def habilitar_manual
    self.update(tipo_voto:2,ha_votado: true)
    tiempo_de_votacion = TiempoDeVotacion.create(persona_id: self.id, votacion_id: self.votacion.id)
  end

  def cabina
    ultima_sesion = self.ultima_sesion
    if ultima_sesion
      return ultima_sesion.cabina
    end
  end

  def puede_ser_candidato
    dif = 8
    ingreso = self.fecha_ingreso
    anio_ingreso = ingreso.year
    mes_ingreso = ingreso.month
    hoy = Date.today
    anio_hoy = hoy.year
    mes_hoy = hoy.month
    if(!self.es_socio)
      return false
    end
    return (anio_hoy - anio_ingreso > dif + 1) || (anio_hoy - anio_ingreso  > dif && mes_hoy > mes_ingreso)
  end


  def self.pueden_ser_candidatos(relation = Persona.all)
    dif = 8
    hoy = Date.today
    anio_hoy = hoy.year
    mes_hoy = hoy.month
    relation.where('(? - extract(year  from fecha_ingreso) > ?) OR (? - extract(year  from fecha_ingreso)>? && ? > extract(month  from fecha_ingreso))', anio_hoy,dif+1,anio_hoy,dif,mes_hoy)
  end

  def self.find_by_rut_string(value)
    find_by_rut_int(rut_to_int(value))
  end

  def self.where_rut_string(value)
    where(rut_int: rut_to_int(value))
  end

  def poderes_validos_recibidos
    poderes_recibidos = self.poderes_recibidos
    poderes_validos = []
    poderes_recibidos.find_each do |pr|
      if pr.valido
        poderes_validos.append(pr)
      end
    end
    poderes_validos
  end

  def voto_propio_disponible
    if self.es_socio
      1
    else
      0
    end
  end


  def votos_totales_disponibles
    self.voto_propio_disponible + self.votos_extra_disponibles
  end


  def votos_extra_disponibles
    asiste = votacion.asiste?(self)
    return 0 unless asiste
    result = self.poderes_validos_recibidos.size
    max_representados = votacion.total_maxima_representacion
    if result > max_representados
      result = max_representados
    end
    result
  end

  def votos_recibidos_totales
    self.votos_recibidos_electronicos + self.votos_recibidos_manuales
  end



end

app/controllers/personas_controller.rb
class PersonasController < ApplicationController
  before_action :set_persona, only: [:show, :edit, :update, :destroy, :eliminar_candidatura, :nomina]
  skip_before_action :login_redirect, only: [:show]

  # GET /personas
  # GET /personas.json
  def index
    authorize_asistencia
    @votacion_id = params[:votacion_id]
    @mensaje = params[:mensaje]
    @votacion = Votacion.find(@votacion_id)
    #@personas = Persona.where(votacion_id: @votacion_id).page(params[:page])
    @filtro = params[:filtro]
    @rut = params[:rut]
    @per = 25
    if @filtro == 'asistentes'
      @personas = @votacion.asistentes
    elsif @filtro == 'no_han_votado'
      @personas = @votacion.personas.no_han_votado
    else
      @personas = @votacion.personas.all
    end
    if @rut and @rut != ''
      @personas = @personas.where_rut_string(@rut)
    end
    @personas = @personas.page(params[:page]).per(@per)
  end

  # GET /personas/1
  # GET /personas/1.json
  def show
    @votacion = @persona.votacion
    @per = 25
    @poderes_enviados = @persona.poderes_enviados.page(params[:page]).per(@per)
    @poderes_recibidos = @persona.poderes_recibidos.page(params[:page]).per(@per)

    @n_poderes_validos_recibidos = @persona.poderes_validos_recibidos.size
    @votos_disponibles = @persona.votos_totales_disponibles

  end

  #POST
  def create_collection
    accepted_formats = [".xls", ".xlsx"]
    if params[:file].nil?
      error_message("¡Error! Debe seleccionar un archivo antes de presionar 'Ingresar'")
      return
    elsif !accepted_formats.include? File.extname(params[:file].original_filename)
      error_message("¡Error! Debe seleccionar un archivo Excel de extensión xls o xlsx")
      return
    end

    @book = Roobook.new(params[:file])
    votacion_id = params[:votacion_id]
    inserts = []
    now = DateTime.now.to_time.strftime("%F %T")
    texto_error = ''
    correctos = 0
    errores = 0
    fila = 0
    @book.each_row do |row|
      if fila > 1
        rut = row[0]
        fecha = row[4]
        valido = !rut.nil? && rut.to_i != 0 && fecha.class == Date
        if valido
          nombre = row[2].gsub(/['"]/, '')
          empresa = row[3].gsub(/['"]/, '')
          puede_ser_representante = row[5].nil?
          inserts.push "(#{rut},'#{nombre}','#{empresa}','#{fecha}',#{votacion_id},#{puede_ser_representante.to_s.upcase},'#{now}','#{now}')"
          correctos += 1
          else
            if rut.nil? or rut.to_i == 0
              texto_error += "fila " + fila.to_s + ": El rut no corresponde a un valor numérico\n"
              errores += 1
            end
          if fecha.class != Date
            texto_error += "fila " + fila.to_s + ": El valor de fecha no es vaĺido\n"
            errores += 1
          end
        end
      end
      fila += 1
    end
    mensaje = "#{correctos} socios cargados correctamente\n#{errores} errores\n"
    if errores > 0
      mensaje += texto_error
    end
    sql = "INSERT IGNORE INTO personas (rut_int, nombre, empresa, fecha_ingreso, votacion_id, puede_ser_representante, created_at, updated_at) VALUES #{inserts.join(',')} ;"
    ActiveRecord::Base.connection.execute sql
    respond_to do |format|
      format.html { redirect_to personas_path(votacion_id: votacion_id, mensaje: mensaje) }
      format.js { }
    end

  end

  def habilitar_voto
    # redirect_to home_index_path(params)
    # return
    @votacion = Votacion.find(params[:votacion_id])
    @cabinas = @votacion.cabinas
    if @cabinas.empty?
      error_message('Error! Para hacer esto, debe tener por lo menos una cabina de votación habilitada')
      return
    end
    if !authorize_vocal || !authorize_votacion_estados(@votacion,[3])
      return
    end
    rut = params[:rut]
    @persona = Persona.where(votacion: @votacion).where("estado != ?",0).find_by_rut_string(rut)
    if @persona.nil?
      error = "El rut #{rut} no corresponde a un asistente de la votación #{@votacion.nombre}"
      error_message(error)
      return
    end
    # if @persona.estado_voto == 1
    #   error = "Error! El asistente de rut #{rut} fue habilitado para votar y aún no está fuera de tiempo"
    #   error_message(error)
    #   return
    #end
    if @persona.estado_voto == 2
      error = "Error! El asistente de rut #{rut} ya votó"
      error_message(error)
      return
    end
    if @persona.estado_voto == 3 and !current_user.es_admin_autorizado
      error = "Error! El asistente de rut #{rut} está fuera de tiempo para votar"
      error_message(error)
      return
    end
    n_cabina = @persona.habilitar
    mensaje = "El asistente #{@persona.rut_string} está habilitado para votar en la cabina número #{n_cabina}"
    respond_to do |format|
      format.js { render inline: "alert('#{mensaje}');window.location='#{vista_vocal_de_mesa_votacion_url(@votacion)}';"}
      format.html {redirect_to vista_vocal_de_mesa_votacion_path(@votacion)}
    end
  end

  def habilitar_voto_manual
    # redirect_to home_index_path(params)
    # return
    @votacion = Votacion.find(params[:votacion_id])
    @cabinas = @votacion.cabinas
    if !authorize_vocal || !authorize_votacion_estados(@votacion,[3])
      return
    end
    rut = params[:rut]
    @persona = Persona.where(votacion: @votacion).where("estado != ?",0).find_by_rut_string(rut)
    if @persona.nil?
      error = "El rut #{rut} no corresponde a un asistente de la votación #{@votacion.nombre}"
      error_message(error)
      return
    end
    if @persona.estado_voto == 1
      error = "Error! El asistente de rut #{rut} ya ingresó a la cabina de votación"
      error_message(error)
      return
    end
    if @persona.estado_voto == 2
      error = "Error! El asistente de rut #{rut} ya votó"
      error_message(error)
      return
    end
    if @persona.estado_voto == 3 and !current_user.es_admin_autorizado
      error = "Error! El asistente de rut #{rut} está fuera de tiempo para votar"
      error_message(error)
      return
    end
    ActiveRecord::Base.transaction do
      @persona.habilitar_manual
      @votacion.total_votos_manuales_segun_votantes += @persona.votos_totales_disponibles
      @votacion.save
    end
    mensaje = "El asistente #{@persona.rut_string} está habilitado para votar manualmente"
    respond_to do |format|
      format.js { render inline: "alert('#{mensaje}');window.location='#{vista_vocal_de_mesa_manual_votacion_url(@votacion)}'" }
      format.html {redirect_to vista_vocal_de_mesa_manual_votacion_path(@votacion)}
    end
  end

  def agregar_asistencia
    # redirect_to home_index_path(params)
    # return
    @votacion = Votacion.find(params[:votacion_id])
    rut = params[:rut]
    @persona = Persona.where(votacion: @votacion).find_by_rut_string(rut)
    if @persona.nil?
      error = "¡Error! El rut #{rut} no corresponde a un socio o representante de la votación #{@votacion.nombre}"
      error_message(error)
      return
    end
    if @persona.estado != 0
      error = "¡Error! El rut #{rut} ya está ingresado como asistente"
      error_message(error)
      return
    end
    if !authorize_asistencia || !authorize_votacion_estados(@votacion,[1])
      return
    end
    @persona.estado = 1
    @persona.hora_asistencia = Time.now
    @lala = @persona.save
    respond_to do |format|
      format.html {redirect_to show_asistentes_votacion_path(@votacion)}
      format.js { render inline: "window.location='#{show_asistentes_votacion_url(@votacion, agregar: true)}';"}
    end
  end

  def eliminar_asistencia
    @persona = Persona.find(params[:persona_id])
    @votacion = @persona.votacion
    @agregar = params[:agregar]
    if !authorize_asistencia || !authorize_votacion_estados(@votacion,[1])
      return
    end
    @persona.estado = 0
    if @persona.save
      redirect_to show_asistentes_votacion_path(@votacion, agregar: @agregar)
    end
  end


  def agregar_candidatura
    # redirect_to home_index_path(params)
    # return
    @votacion = Votacion.find(params[:votacion_id])
    rut = params[:rut]
    @persona = Persona.where(votacion: @votacion).find_by_rut_string(rut)
    if !authorize_tricel || !authorize_votacion_estados(@votacion,[2])
      return
    end
    if @persona.nil?
      error = "¡Error! El rut #{rut} no corresponde a un socio de la cooperativa"
      error_message(error)
      return
    end
    if @persona.estado == 0
      error = "¡Error! El rut #{rut} no corresponde a un asistente a la votación #{@votacion.nombre}"
      error_message(error)
      return
    end
    # if !@persona.puede_ser_representante
    #   error = "¡Error! El socio de rut #{rut} no puede ser candidato"
    #   error_message(error)
    #   return
    # end
    if @persona.estado > 1
      error = "¡Error! El rut #{rut} ya fue ingresado como candidato"
      error_message(error)
      return
    end
    if !@persona.puede_ser_candidato
      error = "El socio #{rut} no cumple con la antiguedad necesaria para ser candidato"
      error_message(error)
      return
    end
    @persona.estado = 2
    if @persona.save
      respond_to do |format|
        format.html {redirect_to votacion_path(@votacion)}
        format.js { render inline: "window.location='#{votacion_url(@votacion)}';"}
      end
    end
  end

  def eliminar_candidatura
    @votacion = @persona.votacion
    if !authorize_tricel || !authorize_votacion_estados(@votacion,[2])
      return
    end
    @persona.estado = 1
    if @persona.save
      redirect_to @votacion
    end
  end


  # GET /personas/new
  def new
    @votacion_id = params[:votacion_id]
    @persona = Persona.new(votacion_id: @votacion_id)
  end

  # GET /personas/1/edit
  def edit
  end

  # POST /personas
  # POST /personas.json
  def create
    # redirect_to home_index_path(params)
    # return
    @persona = Persona.new(persona_params)
    respond_to do |format|
      if @persona.save
        format.html { redirect_to @persona, notice: 'Persona was successfully created.' }

app/helpers/personas_helper.rb
module PersonasHelper
end

app/views/personas/_form.html.erb
<%= form_for(@persona) do |f| %>
  <% if @persona.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@persona.errors.count, "error") %> prohibited this persona from being saved:</h2>

      <ul>
      <% @persona.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :rut_string %><br>
    <%= f.text_field :rut_string %>
  </div>
  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :fecha_ingreso %><br>
    <%= f.date_select :fecha_ingreso, start_year: 1954, end_year: 2015 %>
  </div>
  <%= f.hidden_field :votacion_id %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/personas/_list.html.erb
<div class="col-md-10 col-md-offset-1">
  <div class="listing">

  <% if !@asistentes %>
      <form>
        <input type="radio" id="ver_todos" name="filtro" value="todos" <%= 'checked' if !@filtro %>> Ver todos &nbsp;&nbsp;
        <input type="radio" id="ver_asistentes" name="filtro" value="asistentes" <%= 'checked' if @filtro == 'asistentes'%>> Ver solo asistentes &nbsp;&nbsp;
        <input type="radio" id="ver_no_han_votado" name="filtro" value="no-han-votado"<%= 'checked' if @filtro == 'no_han_votado'%>> Ver solo asistentes que no han votado
      </form>
  <% end %>
  <br>
    <% if !@asistentes %>
        <%= form_tag(personas_path(votacion_id: @votacion.id, filtro: @filtro), method: "get") do %>
            <%= hidden_field_tag 'votacion_id', @votacion.id %>
            <%= hidden_field_tag 'filtro', @filtro %>
            <%= text_field_tag(:rut, nil, placeholder: "Buscar por RUT")%><%= submit_tag 'Buscar', class: 'boton-naranjo' %><br>
        <% end %>
    <% end %>
  <%= paginate @personas %>
<table class="table table-bordered not-fixed">
  <thead>
  <tr>
    <th>N°</th>
    <th width="12%">Rut</th>
    <th width="30%">Nombre</th>
    <th width="20%">Empresa</th>
    <th width="15%">Fecha ingreso</th>

    <th %>Puede ser representante</th>
    <th colspan="1" width="20%"></th>
  </tr>
  </thead>
      <tbody>
      <% @i = 1 %>
      <% @personas.each do |persona| %>
          <tr>
            <td><%= @per*(-1+ @personas.current_page) + @i %></td>
            <td ><%= persona.rut_string %></td>
            <td ><%= persona.nombre %></td>
            <td ><%= persona.empresa %></td>
            <td><%= persona.fecha_ingreso %></td>
            <td><%= boolean_to_s(persona.puede_ser_representante) %></td>
            <td class="td-ver">
              <% if @asistentes && current_user.es_control_asistencia_autorizado && @votacion.estado == 1 %>
                  <%= button_to 'Eliminar asistente', eliminar_asistencia_persona_path(persona_id: persona.id, agregar: @agregar), method: :put, data: {confirm: '¿Seguro/a que desea eliminar este asistente?'},class: 'boton-ver ', 'data-toggle' => 'popover', 'data-trigger' => 'hover' %>
              <% elsif current_user && current_user.es_admin_autorizado %>
                  <%= button_to 'Ver', persona, class: 'boton-ver', method: 'get' %>
                  <% if current_user && current_user.es_admin_autorizado %>
                      <%#= button_to 'Editar', edit_persona_path(persona), class: 'boton-ver ', method: 'put', 'data-toggle' => 'popover', 'data-trigger' => 'hover' %>
                      <%= button_to 'Eliminar', persona, class: 'boton-ver', method: :delete, data: {confirm: '¿Seguro/a que desea eliminar este registro?'}, 'data-toggle' => 'popover', 'data-trigger' => 'hover' %>
                  <% end %>
              <% end %>
            </td>
          </tr>
          <% @i += 1 %>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/personas/create_collection.html.erb
params[:file] --> <%= params[:file] %><br>
<% @book.each_row do |b| %>
 <%= b %><br>
<% end %>

app/views/personas/edit.html.erb
<h1>Editing Persona</h1>

<%= render 'form' %>

<%= link_to 'Show', @persona %> |
<%= link_to 'Back', personas_path %>

app/views/personas/index.html.erb
<div class="mensaje" hidden><%= @mensaje if @mensaje%></div>
<div class="init" hidden></div>
<div class="row titulo-seccion">
  <h3 class="menu-title">
    <span class="thin-underline"><%= @votacion.nombre %></span>
    <small><%= @votacion.fecha_realizacion %></small>
  </h3>
  <h4>Socios y representantes </h4>
</div>


<div class="row">


  <%= render 'list' %>
</div>

app/views/personas/new.html.erb
<h1>New Persona</h1>

<%= render 'form' %>

<%= link_to 'Back', personas_path %>

app/views/personas/show.html.erb
<div class="row titulo-seccion">
  <h3 class="menu-title">
    <span class="thin-underline"><%=@persona.votacion.nombre%></span>
    <small><%= @persona.votacion.fecha_realizacion %></small>
  </h3>

  <div class="no-decor">
        &nbsp; <%= link_to '<span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>'.html_safe,
                           @persona.votacion ,
                           "data-toggle" => "tooltip", "data-placement" => "top",
                           "title" => "Ver la votación", "data-container" => "body"%>
    <% if !current_user %>
        <div class="salir"><%= link_to "<span class=\"exit\">&times;</span> SALIR".html_safe, '/invitado'%></div>
    <% end %>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <div class="label-dashboard">
      <span class="label label-default label-warning"><%= @persona.estado_voto_str %></span>
      <span class="label label-default">
        <% if @persona.es_socio %>
             <%= "Es socio" %>
          <%else%>
            <%="No es socio" %>
          <%end%>
      </span>
      <span class="label label-default">
          <% if @persona.puede_ser_candidato %>
             <%= "Sí puede ser candidato" %>
          <%else%>
            <%="No puede ser candidato" %>
          <%end%>
      </span>

    </div>
  </div>
</div>



<div class="row">
  <div class="col-md-4 col-md-offset-1">
    <div class="listing">
      <h4>Datos Socio</h4>
      <table class="table table-bordered">
        <tbody>
        <tr>
          <th>Rut</th>
          <td><%=  @persona.rut_string %></td>
        </tr>
        <tr>
          <th>Nombre</th>
          <td><%= @persona.nombre %></td>
        </tr>
        <tr>
          <th>Empresa</th>
          <td><%= @persona.empresa %></td>
        </tr>

        <tr>
          <th>Fecha ingreso:</th>
          <td> <%= @persona.fecha_ingreso %></td>
        </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

<% if current_user && current_user.es_vocal_autorizado %>
    <div class="row">
      <div class="col-md-12">
        <div class="row">
          <div class="col-md-12"> <h4>Nómina de representante</h4></div>
        </div>
        <div class="row">
          <div class="col-md-12">
            <%= button_to 'Generar nómina', nomina_persona_path(persona_id: @persona.id), class: 'boton-naranjo', method: :get%>
          </div>
        </div>
      </div>
    </div>
<% end %>

<div class="row">
  <div class="col-md-12">
    <div class="row">
      <div class="col-md-12"> <h4>Votos disponibles</h4></div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <div class="label-dashboard">
          <span class="label label-default"><%= @persona.voto_propio_disponible %> votos propios</span>
          <span class="label label-default" data-container="body" data-toggle="tooltip" data-placement="top" title="Máximo <%= @persona.votacion.total_maxima_representacion %>"><%= @persona.votos_extra_disponibles %> votos por poderes recibidos</span>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <h4>Poderes emitidos</h4>
    <%= render 'poders/list', :@poders => @poderes_enviados %>
    </div>
</div>

<div class="row">
  <div class="col-md-12">
    <h4>Poderes recibidos</h4>
    <%= render 'poders/list', :@poders => @poderes_recibidos %>
  </div>
</div>